#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

set -k

#
# Prefs
#
export PATH=$PATH:/usr/local/opt/go/libexec/bin
export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH
export ANDROID_HOME=/usr/local/opt/android-sdk
export GOPATH=$HOME/code/go
export GITHUB_USERNAME=bransorem
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

get_pw() {
  security 2>&1 >/dev/null find-generic-password -ga $1 \
  |ruby -e 'print $1 if STDIN.gets =~ /^password: "(.*)"$/'
}

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='atom'
export VISUAL='atom'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"


# Alias'

# git status
alias gs="git status -s "
alias cgs="clear && git status -s"

alias getdate='date -j -f "%a %b %d %T %Z %Y" "`date`" "+%s" | pbcopy'
alias list="ls -go | awk '{print \$7;}'"

# RVM
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
